In [3]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection  import train_test_split
from sklearn import preprocessing

## Loadin data

In [6]:
irisdata=pd.read_csv("D:/ML_datasets/iris.csv")
irisdata

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
irisdata.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
irisdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## Preparing X and Y

In [13]:
x=irisdata.iloc[:, 0:4]
y=irisdata.select_dtypes(include=[object])

In [15]:
y.head()

species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

In [17]:
y.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

## Preprocessing

In [20]:
le=preprocessing.LabelEncoder()
y=y.apply(le.fit_transform)
y.head()

species
0        0
1        0
2        0
3        0
4        0

In [22]:
y.species.unique()

array([0, 1, 2])

## Train and Test

In [25]:
X_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.5)
print("Dimension of x-trai", X_train.shape, "x_test", x_test.shape)
y_test.head()

Dimension of x-trai (75, 4) x_test (75, 4)


species
110        2
34         0
137        2
139        2
145        2

In [27]:
mlp=MLPClassifier()

In [29]:
mlp.fit(X_train,y_train)

D:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1105: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [31]:
prediction=mlp.predict(x_test)

In [33]:
print("Confusion matrix", confusion_matrix(y_test, prediction))
print("Classification report", classification_report(y_test,prediction))
print("ACcuracy score", accuracy_score(y_test, prediction))

Confusion matrix [[27  0  0]
 [ 0 21  0]
 [ 0  3 24]]
Classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.88      1.00      0.93        21
           2       1.00      0.89      0.94        27

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

ACcuracy score 0.96
